#!/usr/bin/env bash

# If any command fails, exit immediately with that command's exit status
set -eo pipefail

# Find all changed files for this commit
# Compute the diff only once to save a small amount of time.
CHANGED_FILES=$(git diff --cached --name-only --diff-filter=ACMRTUXB)
# Get only changed files that match our file suffix pattern
get_pattern_files() {
    pattern=$(echo "$*" | sed "s/ /\$\\\|/g")
    echo "$CHANGED_FILES" | { grep "$pattern$" || true; }
}
# Get all changed Python files
PY_FILES=$(get_pattern_files .py)

if [[ -n "$PY_FILES" ]]
then
    pytest -vv
    echo "tests passed."

    black --check $PY_FILES
    echo "black passed."

    ruff check $PY_FILES
    echo "ruff passed."

    svst --check $PY_FILES
    echo "svst passed."

    mypy --check $PY_FILES
    echo "mypy passed."
fi
